CREATE TABLE IF NOT EXISTS public.membros (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    atribuicao character varying(20) NOT NULL,
    nome character varying(120) NOT NULL,
    CONSTRAINT membros_atribuicao_check CHECK (((atribuicao)::text = ANY ((ARRAY['FUNCIONARIO'::character varying, 'GERENTE'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS public.projetos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_inicio date NOT NULL,
    data_real_termino date,
    descricao character varying(1000) NOT NULL,
    nome character varying(160) NOT NULL,
    orcamento_total numeric(19,2) NOT NULL,
    previsao_termino date NOT NULL,
    status_atual character varying(30) NOT NULL,
    gerente_id bigint NOT NULL,
    CONSTRAINT projetos_status_atual_check CHECK (((status_atual)::text = ANY ((ARRAY['EM_ANALISE'::character varying, 'ANALISE_REALIZADA'::character varying, 'ANALISE_APROVADA'::character varying, 'INICIADO'::character varying, 'PLANEJADO'::character varying, 'EM_ANDAMENTO'::character varying, 'ENCERRADO'::character varying, 'CANCELADO'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS public.projeto_membros (
    projeto_id bigint NOT NULL,
    membro_id bigint NOT NULL,
    CONSTRAINT projeto_membros_pkey PRIMARY KEY (projeto_id, membro_id)
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fkhpbq9avhhemwl0i37cfytajpx'
    ) THEN
        ALTER TABLE ONLY public.projetos
            ADD CONSTRAINT fkhpbq9avhhemwl0i37cfytajpx FOREIGN KEY (gerente_id) REFERENCES public.membros(id);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fkdrriu0nvklo6mvkn0jiayvd0m'
    ) THEN
        ALTER TABLE ONLY public.projeto_membros
            ADD CONSTRAINT fkdrriu0nvklo6mvkn0jiayvd0m FOREIGN KEY (projeto_id) REFERENCES public.projetos(id);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fkljyy0m8y00yw74rarohwlwjav'
    ) THEN
        ALTER TABLE ONLY public.projeto_membros
            ADD CONSTRAINT fkljyy0m8y00yw74rarohwlwjav FOREIGN KEY (membro_id) REFERENCES public.membros(id);
    END IF;
END $$;
